### ISSUE TITLE
QuickLook preview failing on macOS Sierra 10.12.2

### ISSUE THREAD

**Issue by dannaf** [tuxu/nbviewer-app#1]
Freshly installed release version 0.1.0 into my /Applications/ folder and opened it once, and the QuickLook feature in Finder doesn't work, just shows the app logo:

![tue feb 21 14 42 19 ist 2017](https://cloud.githubusercontent.com/assets/1812425/23165255/e35a89e6-f843-11e6-9e37-0426509b6a15.png)

**Comment by tuxu** [comment]
I just tried on an almost freshly installed system running Sierra, and the preview worked flawlessly. Please verify that the plugin is correctly registered with QuickLook, as in here:

    $ qlmanage -m plugins | grep jupyter
      org.jupyter.ipynb -> /Applications/Jupyter Notebook Viewer.app/Contents/Library/QuickLook/ipynb-quicklook.qlgenerator (1)

If there is any other QuickLook plugin taking ownership of `ipynb` files, things might not work as expected. You could also try to move the `qlgenerator` inside the app bundle into `/Library/QuickLook`, as described [here](https://github.com/tuxu/ipynb-quicklook).

**Comment by lukka5** [comment]
Same problem here. I solved it running `qlmanage -r` after moving the app to `/Applications/` directory.

**Comment by khalido** [comment]
Quicklook is working fine on MacOS 10.12.6.

**Comment by tuxu** [comment]
Thanks @khalido. I'm going to close this. In most cases either a reboot or `qlmanage -r` should do the trick.
