### ISSUE TITLE
Update nbviewer.js

### ISSUE THREAD

**Issue by improbable22** [tuxu/nbviewer-app#11]
Would it be possible to update to the latest version of nbviewer.js? 

A bug that caused multiple MIME versions of the same graph to be displayed has just been fixed (end of this issue: https://github.com/kokes/nbviewer.js/issues/28) and it would be great to have this available.

**Comment by tuxu** [comment]
Sorry for the delay. But [there](https://github.com/tuxu/nbviewer-app/releases/tag/0.1.3) you go, finally! :tada:

**Comment by improbable22** [comment]
Great, many thanks!
