### ISSUE TITLE
Add LaTeX Support

### ISSUE THREAD

**Issue by frankhome61** [tuxu/nbviewer-app#12]
Is it possible to add LaTeX support?

**Comment by kinoute** [comment]
Any update on this? That would be great.

**Comment by MattiooFR** [comment]
Hey @tuxu thanks for this amazing addon ! Could you implement the last nbviewer.js to add the LaTeX support ? I would have done it myself but I have no idea how to generate the ipynb-quicklook.qlgenerator ...

**Comment by kinoute** [comment]
> Hey @tuxu thanks for this amazing addon ! Could you implement the last nbviewer.js to add the LaTeX support ? I would have done it myself but I have no idea how to generate the ipynb-quicklook.qlgenerator ...

I added latex partially and built the generator. You can find it here: https://github.com/kinoute/macos-setup/tree/master/misc

**Comment by kinoute** [comment]
My PR is here by the way: https://github.com/tuxu/ipynb-quicklook/pull/7

**Comment by MattiooFR** [comment]
Merci beaucoup ! :) I just installed it but I think the old is still in control, I will wait until I restart my computer to see if it changes. I tried `qlmanage -r` already

**Comment by tuxu** [comment]
Hi everybody! Sorry for letting you wait so long. I'll prepare a new release in the next couple of days. Thanks @kinoute for the PR!

**Comment by MattiooFR** [comment]
How can I remove the previous version to install the updated one ?

**Comment by kinoute** [comment]
It's been a while since I installed this. I found out that I have installed various generators in `/Library/Quicklook` and some in `/Users/kinoute/Library/QuickLook`. Don't know why but I guess I had some problems to make them work at that time.

the ipynb-generator is inside the `/Library/Quicklook`.

**Comment by tuxu** [comment]
Hope the new release is more convenient to use 🙂 

`qlmanage -m | grep org.jupyter.ipynb` will tell you which generators are registered. The app bundles the QuickLook generator, so no installation into `/Library/QuickLook` or `~/Library/QuickLook` is required. As far as I can tell, you only need to start the app once to update the registered generator.

**Comment by MattiooFR** [comment]
Oh, I actually had forgotten that there was an installed jupyter notebook viewer. Now I understand why bringing the new ipynb quicklook generator from @kinoute in the Library was having no effect ahah. Thanks for the update ! You rock 💪🏼
