### ISSUE TITLE
Blank screen when launched

### ISSUE THREAD

**Issue by Jwink3101** [tuxu/nbviewer-app#14]
When I open a notebook, I just get a blank window. quicklook works fine but not the viewer.

I is possibly a corporate-enforced something-or-another. Is there a way to debug what's happening? I do not even know what information you would need from me. It happens on all notebook files.

Thanks

**Comment by tuxu** [comment]
Could you please comment on your setup? What version of macOS? What kind of corporate "adjustments" could you think of? Some special firewall, malware checker? There is some JavaScript and CSS loaded from Cloudflare, but I think the app should still work with blocked internet access.

**Comment by tuxu** [comment]
Re: debugging. If you want do dive deep, you could load the project in Xcode and set a break point to [ViewController.swift#L30](https://github.com/tuxu/nbviewer-app/blob/master/Jupyter%20Notebook%20Viewer/ViewController.swift#L30). Then you can check whether the web view is populated with valid data.

**Comment by Jwink3101** [comment]
I do suspect it has to do with some CSS or other loaders. It worked on my home internet connection. Hopefully it is now cached. Does the app respect `HTTPS_PROXY` and `HTTP_PROXY` environmental variables? If not, that may be the issue (and it *should*)

I am surprised that the quick-look extension worked though

**Comment by tuxu** [comment]
The app is using a standard [WebView](https://developer.apple.com/documentation/webkit/webview), which should respect the proxies configured in System Preferences.

I should still find a way to bundle the dependencies in one of the next releases, so that no internet connection and caching is required.
