### ISSUE TITLE
Offline use

### ISSUE THREAD

**Issue by juanfcocontreras** [tuxu/nbviewer-app#15]
Hello,

Could it be possible to embed external css and javascripts (like prism.js) files, just in case there isn't internet connection? When you are offline, you get a white quicklook preview because of this.

Best.

**Comment by tuxu** [comment]
That's a good idea and would also fix #14.

**Comment by tuxu** [comment]
Finally done, part of [0.1.5](https://github.com/tuxu/nbviewer-app/releases/tag/0.1.5).
