### ISSUE TITLE
any plan for windows 10?

### ISSUE THREAD

**Issue by StevenLi-DS** [tuxu/nbviewer-app#19]
This is a very interesting app. I wonder if there is any plan for Windows 10 users? 

I'm using QuickLook on Windows, which supports plug-ins.
https://github.com/QL-Win/QuickLook/wiki/Available-Plugins

**Comment by tuxu** [comment]
Sorry, this app is macOS only. Any port to other operating systems would be a rewrite with Qt, Electron, etc., and my main goal was to keep things very simple and slim.
