### ISSUE TITLE
Simple Fix: Brew dismissed "brew cask install"

### ISSUE THREAD

**Issue by FrancescoSchena** [tuxu/nbviewer-app#26]
Using `$ brew cask install jupyter-notebook-viewer` returns `Error: Unknown command: cask` because it is now deprecated, use `$ brew install --cask jupyter-notebook-viewer` instead.

Thank you for the great work!

**Comment by MohamedElashri** [comment]
Also  `brew install cask  jupyter-notebook-viewer` works

**Comment by tuxu** [comment]
Thanks, it's fixed with #27 by @RayBB.
