### ISSUE TITLE
Feature request: Search for text

### ISSUE THREAD

**Issue by jan-engelmann** [tuxu/nbviewer-app#29]
It would be amazing if with `ctrl` + `f` one could search for text

**Comment by tuxu** [comment]
This actually works in `master`, thanks to #28. I'll upload new binaries soon.

**Comment by jan-engelmann** [comment]
Awesome! Thanks. Looking forward to that

**Comment by tuxu** [comment]
[0.1.5](https://github.com/tuxu/nbviewer-app/releases/tag/0.1.5) 🎉
