### ISSUE TITLE
Adding a cask for nbviewer-app

### ISSUE THREAD

**Issue by y0z** [tuxu/nbviewer-app#3]
Hi.
This app is really useful and I love it :)
However downloading nbviewer-app.zip to install and update the app is little inconvenient.

I think it would be great if installation and upgrade could be done with [homebrew-cask](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md).
Could you please support it?

**Comment by tuxu** [comment]
Good point. I just submitted a PR: https://github.com/caskroom/homebrew-cask/pull/39756.

**Comment by y0z** [comment]
Thank you!

**Comment by AlJohri** [comment]
@tuxu, can you document this in the README? I was searching for `brew cask search nbviewer` when I first came across this app. thanks!

**Comment by tuxu** [comment]
@AlJohri Done!
