### ISSUE TITLE
Doesn't render latex in markdown

### ISSUE THREAD

**Issue by beasteers** [tuxu/nbviewer-app#4]
It would be great if it did.

**Comment by tuxu** [comment]
That's certainly true. There are duplicate issues https://github.com/tuxu/ipynb-quicklook/issues/2 and https://github.com/kokes/nbviewer.js/issues/1. Best would be support in nbviewer.js directly, which serves as the rendering backend.

Actually, I am thinking about adding another backend using jupyter's own nbconvert tool. That would ensure maximum compatibility, and in case something fails, we could still fallback to nbviewer.js.

**Comment by plus2047** [comment]
Hope it render LaTeX too. I writed many LaTeX in my notebooks.
