### ISSUE TITLE
Only the first cell is visible with certain files

### ISSUE THREAD

**Issue by improbable22** [tuxu/nbviewer-app#6]
I just found this program, and am having difficulty with certain notebooks. The ones I have saved myself work fine, but those produced by the Julia package Literate.jl don't seem to work. 

This package turns files like [example.jl](https://github.com/fredrikekre/Literate.jl/blob/master/examples/example.jl) into notebooks like [example.ipynb](https://nbviewer.jupyter.org/github/fredrikekre/Literate.jl/blob/gh-pages/v0.2.1/generated/example.ipynb). I attach an example of what I see. Only the first cell is shown by nbviewer-app, while nteract (the window behind) shows more. 

I don't know which end has the problem here -- it only happens for me with this viewer and such files together. Files created directly in Jupyter work fine. And Jupyter itself works fine with these files. 

![screen shot 2018-05-30 at 3 59 57 pm](https://user-images.githubusercontent.com/29553230/40724950-8d5c63c4-6422-11e8-9256-e32ede950d92.JPG)

**Comment by tuxu** [comment]
Interesting... If you open the same file in Jupyter and then save it, it will correctly show also in nbviewer-app. This is actually a problem with the JSON produced from Literate.jl.. I could trace the problem to the first output cell, where nbviewer.js expects an array, but only a string literal is found [(here, for example)](https://github.com/fredrikekre/Literate.jl/blob/gh-pages/v0.2.1/generated/example.ipynb?short_path=4a7e22b#L43).

Should be an easy fix. I'll look into it.

**Comment by improbable22** [comment]
That I did not think to try, thanks for taking a look. 

Is this something Literate.jl ought to change, to conform to standard, or more of a grey area?

**Comment by tuxu** [comment]
Looking through the notebook file format [docs](https://nbformat.readthedocs.io/en/latest/format_description.html#top-level-structure), the behavior of Literate.jl is totally fine:

> If you intend to work with notebook files directly, you must allow multi-line string fields to be either a string or list of strings.

So this should be fixed in [nbviewer.js](https://github.com/kokes/nbviewer.js), which is used by nbviewer-app to render the notebooks.

**Comment by kokes** [comment]
Thanks for reporting this, I think I've fixed it (and one other related thing), see [#28](https://github.com/kokes/nbviewer.js/issues/28).

**Comment by tuxu** [comment]
Thanks for fixing this, @kokes. I'll merge an updated version of nbviewer.js when #5 is addressed. I'll file a PR if you don't beat me to it 😉

**Comment by tuxu** [comment]
Fixed in 43929a71e7951f51176507570105d972adc125cc
