### ISSUE TITLE
Add Search function

### ISSUE THREAD

**Issue by maahn** [tuxu/nbviewer-app#7]
Thanks for providing this app. Would it be possible to add a search box to search the notebook?

**Comment by tuxu** [comment]
Thanks for the suggestion. I'll look into it.

From what I've found out, there's a [search](https://developer.apple.com/documentation/webkit/webview/1408343-search) method for a WebView (which is used for displaying content), but we would need to implement the UI for performing the search. In the successor of WebView, [WKWebView](https://developer.apple.com/documentation/webkit/wkwebview), there is no built-in search functionality anymore, and it appears to me that one must implement it by injecting JavaScript.

**Comment by gevezex** [comment]
This is pitty. This would really make it complete as search is something I use all the time (and I guess a lot of other people as wel). 
By the way i really like your product.

**Comment by tuxu** [comment]
This is now implemented in `master` thanks to #28 by @fcanas. Time to cut a new release soon 👍

**Comment by gevezex** [comment]
When can we expect the new version, I am really excited. And thnx for the great effort!
